#!/bin/bash

set -eu

PATH="./bin:$PATH"
DEFAULT_WIDTH=480
DEFAULT_FPS=10


declare -a files
files=( $(find source -name [a-z]*.toml) )

for toml in "${files[@]}"; do
    slug="${toml%.*}"

    file=$(toml $toml video.file)
    ext=$(toml $toml video.ext)
    gif="${slug}.gif"
    video="videos/${file}.${ext}"

    if [ ! -f "$video" ]; then
        echo "** $toml:"
        echo "   $video does not exist"
        exit 1
    fi

    if [ ! -f "$gif" ]; then
        start=$(toml $toml video.start)
        duration=$(toml $toml video.duration)

        echo "++ $gif"

        # resize the image, preserving the aspect ratio
        output_width="$(toml $toml output.width)"
        scale="scale=${output_width:-$DEFAULT_WIDTH}:-1"

        # reduce the framerate
        output_fps="$(toml $toml output.fps)"
        fps="fps=${output_fps:-$DEFAULT_FPS}"

        # reduce no. of colours in the uniform palette
        output_colours="$(toml $toml output.colours)"
        max_cols="max_colors=${output_colours:-64}"

        # dithering to improve output
        output_mode="$(toml $toml output.mode)"
        mode="stats_mode=${output_mode:-diff}"
        dither="dither=bayer:bayer_scale=4"
        diff_mode="diff_mode=rectangle"

        filter="[0:v] ${fps},${scale},split [a][b];"
        filter="${filter} [a] palettegen=${max_cols}:${mode} [p];"
        filter="${filter} [b][p] paletteuse=${dither}:${diff_mode}"

        ffmpeg \
            -loglevel warning \
            -ss "$start" \
            -t "$duration" \
            -i "$video" \
            -f gif \
            -filter_complex "$filter" \
            "$gif"
    fi
done
