#!/bin/bash

set -eu

PATH="./bin:$PATH"
DEFAULT_WIDTH=480


declare -a files
files=( $(find source -name [a-z]*.toml) )

for toml in "${files[@]}"; do
    slug="${toml%.*}"

    file=$(toml $toml video.file)
    ext=$(toml $toml video.ext)
    gif="${slug}.gif"
    video="videos/${file}.${ext}"

    if [ ! -f "$video" ]; then
        echo "** $toml:"
        echo "   $video does not exist"
        exit 1
    fi

    if [ ! -f "$gif" ]; then
        start=$(toml $toml video.start)
        duration=$(toml $toml video.duration)

        echo "++ $gif"

        # resize the image, preserving the aspect ratio
        output_width="$(toml $toml output.width)"
        scale="scale=${output_width:-$DEFAULT_WIDTH}:-1"

        filter="[0:v] ${scale}"

        ffmpeg \
            -loglevel warning \
            -ss "$start" \
            -t "$duration" \
            -i "$video" \
            -f gif \
            -filter_complex "$filter" \
            "$gif"
    fi
done
