#!/usr/bin/env bash -euo pipefail


function main {
    local create="$1"
    local path="$(dirname $create)"

    # create the source/episode index files if necessary
    local source="${path%/*}"
    create_source "$source"

    if [ "$source" != "$path" ]; then
        create_episode "$path"
    fi

    gif="$(basename $create)"
    create_gif "$source" "$path" "$gif"
}

function create_gif {
    local source="$1"
    local path="$2"
    local gif="$3"
    local toml="source/$path/$gif.toml"

    if [ -f "$toml" ]; then
        read -p "** $toml exists; overwrite? (y/n) " -n1 overwrite
        echo ''
        [ "$overwrite" != 'y' -a "$overwrite" != Y ] && exit 1
    fi

    cat <<EOF > "$toml"
title = '$(echo "$gif" | sed -e 's/-/ /g')'
published = 2100-01-01T07:00:00Z
EOF
    
    if [ "$source" = "$path" ]; then
        echo "source_fkey = '$source/index'" >> "$toml"
    else
        echo "show_fkey = '$source/index'" >> "$toml"
        echo "episode_fkey = '$path/index'" >> "$toml"
    fi

    cat <<EOF >> "$toml"
tag = [
    'tag',
    'tag2',
]
body_markdown = """

WRITE ME.

"""

[video]
source   = 'file | youtube'
file     = '$path'
ext      = 'm4v'
start    = '0:00:00.0'
duration = '1'
# end      = '00:00:00.0'
# even numbered 16x9 crops:
# 1760:990 1600:900 1440:810 1280:720 1120:630 960:540 800:450 640:360
# video size: REPLACE_SIZE
# crop     = '800:450'

# [palette]
# add = [
#     '#5a7e4c',
#     '#d5dc4b',
# ]
# list = 1
# show = 1

[output]
# brightness = '0'
colours    = '254'
# denoise    = true
# dither     = 'bayer:bayer_scale=0-5'
# dither     = 'floyd_steinberg'
# dither     = 'sierra2'
# dither     = 'sierra2_4a'
# fps        = '12'
# fps        = '18'
fps        = 'original'
loss       = 'no'
# max_size   = 'auto'
# mode       = 'full'
# width      = 'original'
width    = '640'

# [[clip]]
# start = '1'
# end   = '2'

# [[caption]]
# text      = "Looks like I picked the\nwrong week to give up drinking"
# from      = '1'
# to        = '2'
# align     = 'center'
# margin    = '20'
# placement = 'bc'
# size      = '28'
#
##### not required, but can be used if needed
# align     = 'center'
# colour    = 'white'
# font      = 'assistant-semibold.ttf'      # DEFAULT
# font      = 'assistant-extrabold.ttf'     # emphasis
# font      = 'acherusgrotesque-black.otf'  # eurovision
# font      = 'greycliffcf-medium.otf'
# font      = 'greycliffcf-heavy.otf'       # emphasis
# font      = 'lato-black.ttf'              # "TOP. MEN."
# font      = 'oita.otf'                    # Horizon Zero Dawn
# font      = 'poppins-black.ttf'           # Spider-Verse
# font      = 'morlrounded-regular.otf'     # animated
# font      = 'morlrounded-italic.otf'      # animated actions (bonk, scream)
# margin    = '10'
# placement = 'bc'
# size      = '24'
# stroke_colour = 'black'
# stroke_width  = '2'
EOF

    subl -w $toml
    ./script/get_videos $toml

    dimensions=$(
        ffprobe \
            -loglevel error \
            -show_entries stream=width,height \
            -of csv=p=0:s=x \
            videos/$(bin/toml $toml video.file).$(bin/toml $toml video.ext) \
                | head -1
    )
    sed \
        -i '' \
        -e "s/REPLACE_SIZE/$(echo $dimensions | sed -e 's/x/:/')/" \
            $toml

    subl $toml
    make

}

function create_source {
    local source="$1"

    mkdir -p "source/$source"
    if [ ! -f "source/$source/index.markdown" ]; then
        cat <<EOF > "source/$source/index.markdown"
\`\`\`
title = '$source'
year = '0000'
type = 'act agency event game internet movie recording-artist tv-show youtube'
source = true
imdb = 'tt0000000'
wikipedia = '__'

# homepage = 'https://www.guerrilla-games.com/play/horizon'
# playlist = 'PL--PgETgAz5FGoatB9KQzbnpv0bgZqU2l'
# url = 'https://vole.wtf/buttystock/'
# video = 'HU2ftCitvyQ'
\`\`\`

Write something here. If you want to.
EOF
        subl "source/$source/index.markdown"
    fi
}

function create_episode {
    local episode="$1"
    local source="${episode%/*}"

    mkdir -p "source/$episode"
    if [ ! -f "source/$episode/index.markdown" ]; then
        cat <<EOF > "source/$episode/index.markdown"
\`\`\`
title = 'TITLE'
type = 'tv-episode'
show_fkey = '$source/index'
season = 1
episode = 1
# imdb = 'tt0000000'
# wikipedia = '__'

type = 'music-video'
artist_fkey = '$source/index'
video = '5Dho47jZS9U'
source = true
\`\`\`

Write something here. If you want to.
EOF
        subl "source/$episode/index.markdown"
    fi
}

main "$1"
