#!/usr/bin/env -S bash -euo pipefail

match="$1"
push="$2"


today=$(date +'%Y-%m-%d')

declare -a sources
IFS=$'\n' sources=($( rg published source | grep ^source/$match ))

for source in "${sources[@]}"; do
    filename=$(echo $source | cut -d: -f1)
    published=$(echo $source | cut -d\  -f3)

    if [[ $published > $today ]]; then
        new_date=$(gdate +'%Y-%m-%d' --date="$published + $push")
        sed -i '' \
            -e "s/published = ....-..-../published = ${new_date}/" \
                $filename
        echo "++ $filename pushed to $new_date"
    fi
done
