#!/usr/bin/env -S bash -euo pipefail

start="$1"
push="$2"

declare -a files
last_scheduled=$(
    rg --no-filename published source \
        | grep -v 2100-01-01 \
        | sort -u \
        | tail -1 \
        | sed -e 's/published = //' -e 's/T.*Z//'
)
decrease=0
datestamp=''

while [ "$datestamp" != "$start" ]; do
    datestamp=$(gdate +'%Y-%m-%d' --date="$last_scheduled $decrease days")

    files=($(
        rg --files-with-matches published.*$datestamp source \
            || echo ''
    ))
    for file in "${files[@]}"; do
        new_date="$(gdate +'%Y-%m-%d' --date="$datestamp $push days")"
        sed -i '' \
            -e "s/^published = ${datestamp}.*/published = ${new_date}T07:00:00Z/" \
            "$file"
        echo "++ $new_date $file"
    done

    ((decrease=decrease-1))
done
