#!/bin/bash

set -eu

# clean the output dir
[ -d output ] &&
    rm -rf output

# update the site's CSS and determine the sha1 stamp to use
# to make the file permanent
echo "== update CSS"
flourish generate /css/site.css
sha=$( shasum -a 256 output/css/site.css | cut -c1-7 )
cp output/css/site.css output/css/site.${sha}.css
flourish upload
echo \
    "<link rel='stylesheet' href='/css/site.${sha}.css'>" \
        > fragments/default/head_css_sitewide.html

# generate the site
echo "== generate"
flourish generate -v

# push the site
echo "== upload"
flourish upload

echo \
    "<link rel='stylesheet' href='/css/site.css'>" \
        > fragments/default/head_css_sitewide.html
