#!/bin/bash

PATH="./bin:$PATH"

# python --version
# python -c "import platform; print('Arch:', platform.machine())"
# python -c "
# from importlib.metadata import version
# from PIL import features
# print('Pillow:', version('Pillow'))
# print('FreeType:', features.version('freetype2'))
# print('HarfBuzz:', features.version('harfbuzz'))
# print('basic-colormath:', version('basic-colormath'))
# print('flourish:', version('flourish'))
# print('imagequant:', version('imagequant'))
# "
# echo ""
# sysctl -n machdep.cpu.brand_string
# echo ""
# ffmpeg -version
# ffmpeg -buildconf
# echo ""
# echo "Linked libraries:"
# otool -L "$(which ffmpeg)" | grep -E '(zimg|x265|x264|videotoolbox)' || echo "  (none matched filter)"
# echo ""

declare -a tests
blue="\e[34m"
reset="\e[0m"
success=0

printf "=== ${blue}pytest${reset}\n"
pytest tests/*.py -v
let "success = success + $?"

# Use parallel jobs if GNU parallel is available
jobs_arg=""
if command -v parallel &>/dev/null; then
    jobs_arg="--jobs 8"
fi

if [ -n "$*" ]; then
    tests=( "$@" )
else
    tests=( $(echo tests/*.bats) )
fi

for test in "${tests[@]}"; do
    printf "=== ${blue}%s${reset}\n" $test
    bats $jobs_arg $test
    let "success = success + $?"
done

exit $success
