#!/usr/bin/env python

from datetime import datetime, timezone
import os
from flourish import Flourish
import random
import requests
import sys
import time
import tweepy


auth = tweepy.OAuthHandler(
        os.environ['CONSUMER_KEY'],
        os.environ['CONSUMER_SECRET'],
    )
auth.set_access_token(
        os.environ['ACCESS_TOKEN'],
        os.environ['ACCESS_TOKEN_SECRET'],
    )
api = tweepy.API(auth)

today = datetime.now().replace(
        hour=0,
        minute=0,
        second=0,
        tzinfo=timezone.utc,
    )
now = datetime.now().replace(
        tzinfo=timezone.utc,
    )

sources = {}
fl = Flourish()
for gif in fl.sources.filter(published__gte=today).order_by('published'):
    # don't tweet the morning's GIF again
    elapsed = now - gif.published
    if (elapsed.seconds // 3600) > 2:
        continue

    try:
        source = gif.show.title
    except:
        source = gif.source.title
    if source not in sources:
        sources[source] = 1
    else:
        sources[source] += 1
    description = gif.body_markdown.replace('\n', ' ')
    url = gif.absolute_url

    # don't tweet if the publication has failed
    req = requests.get(url)
    if req.status_code != 200:
        sys.exit('** not published: %s' % url)

    media = 'source%s.gif' % gif.path
    intro = "Today's"
    if sources[source] == 2:
        intro = "Today's second"
    if sources[source] > 2:
        intro = 'And another'
    tweet = "%s %s GIF: %s" % (
            intro,
            source,
            description,
        )

    # take care not to overwhelm twitter's posting limit
    if len(tweet) > 250:
        tweet = '%s…' % tweet[:249]

    tweet += '\n\n%s' % url

    print('%s\n----------\n' % tweet)
    upload = api.media_upload(media)
    api.update_status(tweet, media_ids=[upload.media_id_string])
    time.sleep(random.randint(60,180))
