name: Run tests

on:
  push:

jobs:
  tests:
    name: Run the tests
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          brew install bash bats-core gifsicle imagemagick yq
          brew tap homebrew-ffmpeg/ffmpeg
          brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-zimg

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Configure pip caching
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download test video
        run: |
          mkdir -p videos
          curl -o videos/HU2ftCitvyQ.mp4 https://bumph.cackhanded.net/HU2ftCitvyQ.mp4

      - name: Use CI fixtures
        run: |
          cp tests/gifs/ci-sol-levante-hdr.gif tests/gifs/sol-levante-hdr.gif

      - name: Run tests
        run: |
          make test

      - name: Upload failed test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failed-tests
          path: temp/
